spring:
    application:
        name: bank
    datasource:
        password: postgres
        url: jdbc:postgresql://127.0.0.1:5432/bank
        username: postgres
        driver-class-name: org.postgresql.Driver
#    jpa:
#        show-sql: true
#        properties:
#            hibernate:
#                format_sql: true
