### GET Users
GET http://localhost:8080/bank/users

### GET Accounts
GET http://localhost:8080/bank/accounts

### Transfer Race Condition
GET http://localhost:8080/bank/transfer-race-condition

### Transfer Sequential
GET http://localhost:8080/bank/transfer-sequential
